Repository adalbertobrant/SecretGameNumber, pull requests merged in 2025-10, with the labels that each got.

#17 feat: added localization support with portuguese + english with local…
  app.js
  index.html
  locale.js
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, feature

#22 docs: Add Code of Conduct link to README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#23 docs: Fix typos and broken links in README.md
  CONTRIBUTING.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#24 docs: Adjust informal tone in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#25 feat: Add and style high score display
  app.js
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, feature

#26 Docs: Update standardize branch naming rule in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#28 complete MERN migration
  .env.example
  .gitignore
  README-MERN.md
  backend/controllers/user.controller.js
  backend/middleware/auth.middleware.js
  backend/middleware/db.middleware.js
  backend/models/user.model.js
  backend/routes/user.routes.js
  backend/server.js
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/CreditsModal.js
  frontend/src/components/Game.js
  frontend/src/components/Login.js
  frontend/src/components/Navbar.js
  frontend/src/components/Register.js
  frontend/src/context/AuthContext.js
  frontend/src/img/JS Game.html
  frontend/src/img/Ruido.png
  frontend/src/img/bg.png
  frontend/src/img/code.png
  frontend/src/img/ia.png
  frontend/src/index.js
  package.json
  start.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, feature

#33 feat: Allow Enter key to restart game
  app.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, feature

#31 #10 Various Option Added
  app.js
  index.html
  locale.js
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, feature

#36 feat: allow submitting guess with Enter key when input field is focused
  app.js
Labels: hacktoberfest-accepted, hacktoberfest, feature

#37 docs: Adiciona link do Código de Conduta ao CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest
